version: "3.9"
services:
  # Backend (API)
  hotelbitsserver:
    build: ./server
    ports:
      - "4000:4000"
    links:
      - hotelbitsserver

  # Frontend (React)
  hotelbitsclient:
    image:
    ports:
      - "3000:3000"
    links:
      - hotelbitsclient

  # Base de datos (Postgres)
  hotelbitsdb:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hotelbits
      - POSTGRES_PASSWORD=hotelbits264
      - POSTGRES_DB=hotelbits
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: